import { describe, test, expect } from "bun:test";
import { generateSiteFiles, generateIndexHtml, generatePackageJson } from "./site-generator";
import type { PageLayout } from "../agents/site-builder";

describe("site-generator", () => {
  const sampleLayout: PageLayout = {
    title: "My Test Site",
    description: "A test site generated by AI",
    components: [
      {
        component: "Stack",
        props: { direction: "vertical", gap: "md", align: "stretch", justify: "start" },
        children: [
          {
            component: "Text",
            props: { content: "Welcome to My Site", variant: "h1", weight: "bold", align: "center" },
          },
          {
            component: "Card",
            props: { title: "About", padding: "md" },
            children: [
              {
                component: "Text",
                props: { content: "This is an AI-generated website.", variant: "body", weight: "normal", align: "left" },
              },
            ],
          },
          {
            component: "Button",
            props: { variant: "primary", size: "lg", disabled: false, loading: false, label: "Get Started" },
          },
        ],
      },
    ],
  };

  describe("generateSiteFiles", () => {
    test("produces all required files", () => {
      const files = generateSiteFiles(sampleLayout);

      expect(files["src/App.tsx"]).toBeDefined();
      expect(files["src/components.tsx"]).toBeDefined();
      expect(files["src/index.tsx"]).toBeDefined();
      expect(files["index.html"]).toBeDefined();
      expect(files["package.json"]).toBeDefined();
    });

    test("App.tsx imports all used components", () => {
      const files = generateSiteFiles(sampleLayout);
      const appCode = files["src/App.tsx"];

      expect(appCode).toContain("import { Button, Card, Stack, Text }");
      expect(appCode).toContain('from "./components"');
    });

    test("App.tsx renders valid JSX structure", () => {
      const files = generateSiteFiles(sampleLayout);
      const appCode = files["src/App.tsx"];

      // Should have a function component
      expect(appCode).toContain("function App()");
      expect(appCode).toContain("export default App");

      // Should have the component tags
      expect(appCode).toContain("<Stack");
      expect(appCode).toContain("<Text");
      expect(appCode).toContain("<Card");
      expect(appCode).toContain("<Button");

      // Stack and Card should have closing tags (they have children)
      expect(appCode).toContain("</Stack>");
      expect(appCode).toContain("</Card>");

      // Button should be self-closing (no children support)
      expect(appCode).toContain("<Button");
      expect(appCode).toContain("/>");
    });

    test("App.tsx renders component props correctly", () => {
      const files = generateSiteFiles(sampleLayout);
      const appCode = files["src/App.tsx"];

      expect(appCode).toContain('direction="vertical"');
      expect(appCode).toContain('gap="md"');
      expect(appCode).toContain('content="Welcome to My Site"');
      expect(appCode).toContain('variant="h1"');
      expect(appCode).toContain('variant="primary"');
      expect(appCode).toContain('label="Get Started"');
    });

    test("App.tsx renders boolean props correctly", () => {
      const files = generateSiteFiles(sampleLayout);
      const appCode = files["src/App.tsx"];

      // disabled=false and loading=false should render as {false}
      expect(appCode).toContain("disabled={false}");
      expect(appCode).toContain("loading={false}");
    });

    test("components.tsx exports all used component stubs", () => {
      const files = generateSiteFiles(sampleLayout);
      const components = files["src/components.tsx"];

      expect(components).toContain("export function Button");
      expect(components).toContain("export function Card");
      expect(components).toContain("export function Stack");
      expect(components).toContain("export function Text");

      // Should NOT include unused components
      expect(components).not.toContain("export function Modal");
      expect(components).not.toContain("export function Badge");
    });

    test("generates base CSS styles", () => {
      const files = generateSiteFiles(sampleLayout);
      const css = files["src/styles.css"];

      expect(css).toBeDefined();
      expect(css).toContain(":root");
      expect(css).toContain("--color-primary");
      expect(css).toContain(".btn");
      expect(css).toContain(".card");
      expect(css).toContain(".stack");
      expect(css).toContain(".text-h1");
      expect(css).toContain(".badge");
      expect(css).toContain(".alert");
      expect(css).toContain(".spinner");
      expect(css).toContain(".separator");
      expect(css).toContain(".tabs");
      expect(css).toContain(".tooltip");
      expect(css).toContain(".avatar");
    });

    test("index.tsx imports styles.css", () => {
      const files = generateSiteFiles(sampleLayout);
      const entry = files["src/index.tsx"];
      expect(entry).toContain('./styles.css');
    });

    test("index.tsx has proper SolidJS entry point", () => {
      const files = generateSiteFiles(sampleLayout);
      const entry = files["src/index.tsx"];

      expect(entry).toContain('import { render } from "solid-js/web"');
      expect(entry).toContain('import App from "./App"');
      expect(entry).toContain('document.getElementById("app")');
      expect(entry).toContain("render(() => <App />, root)");
    });

    test("handles nested children correctly", () => {
      const files = generateSiteFiles(sampleLayout);
      const appCode = files["src/App.tsx"];

      // Card is inside Stack, Text is inside Card
      // Verify nesting by checking indentation increases
      const lines = appCode.split("\n");
      const stackLine = lines.findIndex((l) => l.includes("<Stack"));
      const cardLine = lines.findIndex((l) => l.includes("<Card"));
      const textLine = lines.findIndex((l, i) => i > cardLine && l.includes("<Text") && l.includes("AI-generated"));

      expect(stackLine).toBeGreaterThan(-1);
      expect(cardLine).toBeGreaterThan(stackLine);
      expect(textLine).toBeGreaterThan(cardLine);
    });

    test("handles layout with no children components", () => {
      const minLayout: PageLayout = {
        title: "Minimal",
        description: "Just a button",
        components: [
          {
            component: "Button",
            props: { variant: "default", size: "md", disabled: false, loading: false, label: "Click" },
          },
        ],
      };

      const files = generateSiteFiles(minLayout);
      expect(files["src/App.tsx"]).toContain("<Button");
      expect(files["src/App.tsx"]).toContain("/>");
    });

    test("handles special characters in text content", () => {
      const layout: PageLayout = {
        title: "Special Chars",
        description: "Test",
        components: [
          {
            component: "Text",
            props: { content: 'Hello "World" & <Friends>', variant: "body", weight: "normal", align: "left" },
          },
        ],
      };

      const files = generateSiteFiles(layout);
      const appCode = files["src/App.tsx"];

      // Should escape special characters in JSX attributes
      expect(appCode).toContain("&amp;");
      expect(appCode).toContain("&lt;");
      expect(appCode).toContain("&gt;");
      expect(appCode).toContain("&quot;");
    });
  });

  describe("generateIndexHtml", () => {
    test("generates valid HTML with title", () => {
      const html = generateIndexHtml("Test Page");

      expect(html).toContain("<!DOCTYPE html>");
      expect(html).toContain("<title>Test Page</title>");
      expect(html).toContain('<div id="app"></div>');
      expect(html).toContain('type="module"');
      expect(html).toContain("src/index.tsx");
    });

    test("escapes HTML in title", () => {
      const html = generateIndexHtml('My <script>alert("xss")</script> Page');

      expect(html).not.toContain("<script>alert");
      expect(html).toContain("&lt;script&gt;");
    });

    test("includes viewport meta tag", () => {
      const html = generateIndexHtml("Test");

      expect(html).toContain('name="viewport"');
      expect(html).toContain("width=device-width");
    });
  });

  describe("generatePackageJson", () => {
    test("generates valid JSON", () => {
      const pkgStr = generatePackageJson("my-site");
      const pkg = JSON.parse(pkgStr);

      expect(pkg.name).toBe("my-site");
      expect(pkg.version).toBe("1.0.0");
      expect(pkg.private).toBe(true);
      expect(pkg.type).toBe("module");
    });

    test("includes SolidJS dependency", () => {
      const pkg = JSON.parse(generatePackageJson("test"));

      expect(pkg.dependencies["solid-js"]).toBeDefined();
    });

    test("includes build tooling", () => {
      const pkg = JSON.parse(generatePackageJson("test"));

      expect(pkg.devDependencies.vite).toBeDefined();
      expect(pkg.devDependencies["vite-plugin-solid"]).toBeDefined();
      expect(pkg.devDependencies.typescript).toBeDefined();
    });

    test("includes dev and build scripts", () => {
      const pkg = JSON.parse(generatePackageJson("test"));

      expect(pkg.scripts.dev).toBeDefined();
      expect(pkg.scripts.build).toBeDefined();
    });
  });
});
