// ── Components ───────────────────────────────────────────────────────
export {
  Button,
  ButtonPropsSchema,
  Input,
  InputPropsSchema,
  Textarea,
  TextareaPropsSchema,
  Card,
  CardPropsSchema,
  Modal,
  ModalPropsSchema,
  Stack,
  StackPropsSchema,
  Text,
  TextPropsSchema,
  Badge,
  BadgePropsSchema,
  Avatar,
  AvatarPropsSchema,
  Spinner,
  SpinnerPropsSchema,
  Alert,
  AlertPropsSchema,
  Tabs,
  TabsPropsSchema,
  TabItemSchema,
  Select,
  SelectPropsSchema,
  SelectOptionSchema,
  Toggle,
  TogglePropsSchema,
  Tooltip,
  TooltipPropsSchema,
  Separator,
  SeparatorPropsSchema,
} from "./components";

export type {
  ButtonProps,
  ButtonSchemaProps,
  InputProps,
  InputSchemaProps,
  TextareaProps,
  TextareaSchemaProps,
  CardProps,
  CardSchemaProps,
  ModalProps,
  ModalSchemaProps,
  StackProps,
  StackSchemaProps,
  TextProps,
  TextSchemaProps,
  BadgeProps,
  BadgeSchemaProps,
  AvatarProps,
  AvatarSchemaProps,
  SpinnerProps,
  SpinnerSchemaProps,
  AlertProps,
  AlertSchemaProps,
  TabsProps,
  TabItem,
  TabsSchemaProps,
  SelectProps,
  SelectOption,
  SelectSchemaProps,
  ToggleProps,
  ToggleSchemaProps,
  TooltipProps,
  TooltipSchemaProps,
  SeparatorProps,
  SeparatorSchemaProps,
} from "./components";

// ── Schema Registry (AI Composability) ───────────────────────────────
export {
  ComponentRegistry,
  ComponentNameSchema,
  getComponentSchema,
  validateComponentProps,
} from "./schemas";

export type { ComponentName } from "./schemas";

// ── Renderer ─────────────────────────────────────────────────────────
export { ComponentRenderer, PageRenderer } from "./renderer";
export type { ComponentRendererProps, PageRendererProps } from "./renderer";
