/**
 * Unit tests for the Signal Bus P1 deploy event emitter (E3 / E4).
 *
 * The emitter is best-effort fire-and-forget HTTP POST to Gluecron; these
 * tests pin its wire-contract obligations without touching the network:
 *
 *   - URL and bearer Authorization header are correctly composed
 *   - `deploy.succeeded` body shape is valid per the wire contract
 *   - `deploy.failed` body shape is valid per the wire contract (incl.
 *     errorCategory + errorSummary truncation)
 *   - missing env vars → no-op, no fetch call, no throw
 *   - fetch rejection is swallowed (never breaks the deploy)
 *   - eventId is a valid UUID v4 and stable for a single call
 *
 * Follows the dep-injection seam in `deploy-event-emitter.ts` (`fetchImpl`,
 * `getEnv`, `uuid`, `now`) rather than monkey-patching globals.
 */

import { beforeEach, describe, expect, test } from "bun:test";
import {
  __resetMissingEnvWarnedForTests,
  emitDeployFailed,
  emitDeploySucceeded,
} from "./deploy-event-emitter";

// ── Shared fetch recorder ──────────────────────────────────────────────

interface FetchCall {
  url: string;
  init: RequestInit | undefined;
}

function makeFetch(
  responder: (call: FetchCall) => Response | Promise<Response> = () =>
    new Response(JSON.stringify({ ok: true, duplicate: false }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    }),
): { calls: FetchCall[]; fn: typeof fetch } {
  const calls: FetchCall[] = [];
  const fn = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = typeof input === "string" ? input : input.toString();
    const call: FetchCall = { url, init };
    calls.push(call);
    return responder(call);
  }) as typeof fetch;
  return { calls, fn };
}

// Deterministic env getter for the happy-path tests. Both env vars present.
const goodEnv = (name: string): string | undefined => {
  if (name === "GLUECRON_EVENT_URL") return "https://gluecron.test";
  if (name === "CRONTECH_EVENT_TOKEN") return "test-token-abc";
  return undefined;
};

// Deterministic UUID + ISO timestamp for stable assertions.
const FIXED_UUID = "11111111-2222-4333-8444-555555555555";
const FIXED_TIMESTAMP = "2026-04-15T12:00:00.000Z";

beforeEach(() => {
  __resetMissingEnvWarnedForTests();
});

// ── Tests ──────────────────────────────────────────────────────────────

describe("emitDeploySucceeded", () => {
  test("POSTs to Gluecron with correct URL, headers, and body shape", async () => {
    const { calls, fn } = makeFetch();

    await emitDeploySucceeded(
      {
        repository: "ccantynz-alt/example",
        sha: "a".repeat(40),
        deploymentId: "dep-123",
        durationMs: 4200,
        logsUrl: "https://logs.test/dep-123",
      },
      {
        fetchImpl: fn,
        getEnv: goodEnv,
        uuid: () => FIXED_UUID,
        now: () => FIXED_TIMESTAMP,
      },
    );

    expect(calls).toHaveLength(1);
    const [call] = calls;
    expect(call!.url).toBe("https://gluecron.test/api/events/deploy");

    const headers = call!.init?.headers as Record<string, string>;
    expect(headers["Authorization"]).toBe("Bearer test-token-abc");
    expect(headers["Content-Type"]).toBe("application/json");
    expect(call!.init?.method).toBe("POST");

    const body = JSON.parse(call!.init?.body as string) as Record<string, unknown>;
    expect(body).toEqual({
      event: "deploy.succeeded",
      eventId: FIXED_UUID,
      repository: "ccantynz-alt/example",
      sha: "a".repeat(40),
      environment: "production",
      deploymentId: "dep-123",
      timestamp: FIXED_TIMESTAMP,
      durationMs: 4200,
      logsUrl: "https://logs.test/dep-123",
    });
    // Required per wire contract — NOT present on succeeded.
    expect(body["errorCategory"]).toBeUndefined();
    expect(body["errorSummary"]).toBeUndefined();
  });

  test("eventId is a valid UUID v4 when generated by crypto.randomUUID()", async () => {
    const { calls, fn } = makeFetch();

    await emitDeploySucceeded(
      {
        repository: "owner/name",
        sha: "b".repeat(40),
        deploymentId: "dep-uuid-check",
      },
      { fetchImpl: fn, getEnv: goodEnv },
    );

    const body = JSON.parse(calls[0]!.init?.body as string) as { eventId: string };
    // RFC 4122 v4 shape: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx
    expect(body.eventId).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
  });
});

describe("emitDeployFailed", () => {
  test("POSTs deploy.failed with errorCategory + errorSummary and truncates to 500 chars", async () => {
    const { calls, fn } = makeFetch();
    const longSummary = "x".repeat(1000);

    await emitDeployFailed(
      {
        repository: "owner/name",
        sha: "c".repeat(40),
        deploymentId: "dep-err-1",
        errorCategory: "runtime",
        errorSummary: longSummary,
        durationMs: 17,
      },
      {
        fetchImpl: fn,
        getEnv: goodEnv,
        uuid: () => FIXED_UUID,
        now: () => FIXED_TIMESTAMP,
      },
    );

    expect(calls).toHaveLength(1);
    const body = JSON.parse(calls[0]!.init?.body as string) as Record<string, unknown>;

    expect(body["event"]).toBe("deploy.failed");
    expect(body["eventId"]).toBe(FIXED_UUID);
    expect(body["errorCategory"]).toBe("runtime");
    expect((body["errorSummary"] as string).length).toBe(500);
    expect(body["durationMs"]).toBe(17);
    expect(body["environment"]).toBe("production");
    expect(body["timestamp"]).toBe(FIXED_TIMESTAMP);

    const headers = calls[0]!.init?.headers as Record<string, string>;
    expect(headers["Authorization"]).toBe("Bearer test-token-abc");
  });
});

describe("env-var handling", () => {
  test("missing GLUECRON_EVENT_URL → no-op, no fetch call", async () => {
    const { calls, fn } = makeFetch();

    await emitDeploySucceeded(
      { repository: "owner/name", sha: "d".repeat(40), deploymentId: "dep-noenv-1" },
      {
        fetchImpl: fn,
        getEnv: (name) =>
          name === "CRONTECH_EVENT_TOKEN" ? "some-token" : undefined,
      },
    );

    expect(calls).toHaveLength(0);
  });

  test("missing CRONTECH_EVENT_TOKEN → no-op, no fetch call", async () => {
    const { calls, fn } = makeFetch();

    await emitDeployFailed(
      {
        repository: "owner/name",
        sha: "e".repeat(40),
        deploymentId: "dep-noenv-2",
        errorCategory: "config",
        errorSummary: "bad config",
      },
      {
        fetchImpl: fn,
        getEnv: (name) =>
          name === "GLUECRON_EVENT_URL" ? "https://gluecron.test" : undefined,
      },
    );

    expect(calls).toHaveLength(0);
  });
});

describe("failure resilience", () => {
  test("fetch rejection is swallowed — emitter never throws", async () => {
    const boom = (async () => {
      throw new Error("connection refused");
    }) as unknown as typeof fetch;

    // Must not throw, must not reject.
    await expect(
      emitDeploySucceeded(
        {
          repository: "owner/name",
          sha: "f".repeat(40),
          deploymentId: "dep-reject",
        },
        { fetchImpl: boom, getEnv: goodEnv },
      ),
    ).resolves.toBeUndefined();
  });

  test("non-2xx response does NOT throw", async () => {
    const { fn } = makeFetch(
      () => new Response("bad request", { status: 400 }),
    );

    await expect(
      emitDeployFailed(
        {
          repository: "owner/name",
          sha: "a".repeat(40),
          deploymentId: "dep-400",
          errorCategory: "config",
          errorSummary: "nope",
        },
        { fetchImpl: fn, getEnv: goodEnv },
      ),
    ).resolves.toBeUndefined();
  });
});
