import { z } from "zod";

export type Severity = "low" | "medium" | "high" | "critical";

export type RepoPriority = "critical" | "high" | "medium";

export type RepoCategory = "framework" | "backend" | "api" | "ai";

export const IntelligenceItemSchema = z.object({
  id: z.string(),
  source: z.string(),
  title: z.string(),
  description: z.string(),
  url: z.string(),
  severity: z.enum(["low", "medium", "high", "critical"]),
  tags: z.array(z.string()),
  metadata: z.record(z.string(), z.unknown()),
  collectedAt: z.string(),
});

export type IntelligenceItem = z.infer<typeof IntelligenceItemSchema>;

export interface CollectorResult {
  source: string;
  items: IntelligenceItem[];
  collectedAt: string;
  success: boolean;
  error: string | undefined;
  durationMs: number;
}

export interface Collector {
  name: string;
  cronExpression: string;
  intervalMs: number;
  collect(): Promise<CollectorResult>;
}

export const TrackedRepoSchema = z.object({
  owner: z.string(),
  repo: z.string(),
  displayName: z.string(),
  priority: z.enum(["critical", "high", "medium"]),
  category: z.enum(["framework", "backend", "api", "ai"]),
  description: z.string(),
  defaultBranch: z.string(),
  lastKnownRelease: z.string().nullable(),
  lastKnownReleaseAt: z.string().nullable(),
  lastCommitCheckAt: z.string().nullable(),
  baselineCommitsPerWeek: z.number().nullable(),
});

export type TrackedRepo = z.infer<typeof TrackedRepoSchema>;

export const TrackedReposFileSchema = z.object({
  repos: z.array(TrackedRepoSchema),
  lastUpdated: z.string().nullable(),
  schemaVersion: z.number(),
});

export type TrackedReposFile = z.infer<typeof TrackedReposFileSchema>;

/** Static fallback list used when tracked-repos.json cannot be loaded. */
export const DEFAULT_TRACKED_REPOS: TrackedRepo[] = [
  {
    owner: "vercel",
    repo: "next.js",
    displayName: "Next.js",
    priority: "critical",
    category: "framework",
    description: "React framework for production.",
    defaultBranch: "canary",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "remix-run",
    repo: "remix",
    displayName: "Remix",
    priority: "high",
    category: "framework",
    description: "Full-stack web framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "sveltejs",
    repo: "kit",
    displayName: "SvelteKit",
    priority: "high",
    category: "framework",
    description: "Full-stack Svelte framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "QwikDev",
    repo: "qwik",
    displayName: "Qwik",
    priority: "medium",
    category: "framework",
    description: "Resumable framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "withastro",
    repo: "astro",
    displayName: "Astro",
    priority: "high",
    category: "framework",
    description: "Content-focused web framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "honojs",
    repo: "hono",
    displayName: "Hono",
    priority: "critical",
    category: "backend",
    description: "Ultrafast web framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "solidjs",
    repo: "solid",
    displayName: "SolidJS",
    priority: "critical",
    category: "framework",
    description: "Our primary frontend framework.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "trpc",
    repo: "trpc",
    displayName: "tRPC",
    priority: "critical",
    category: "api",
    description: "End-to-end typesafe APIs.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "vercel",
    repo: "ai",
    displayName: "Vercel AI SDK",
    priority: "critical",
    category: "ai",
    description: "AI SDK for streaming and generative UI.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "langchain-ai",
    repo: "langchainjs",
    displayName: "LangChain JS",
    priority: "high",
    category: "ai",
    description: "JS framework for LLM applications.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  // ── Dev Platform Competitors (Crontech direct rivals) ────────────
  {
    owner: "cloudflare",
    repo: "workers-sdk",
    displayName: "Cloudflare Workers SDK",
    priority: "critical",
    category: "backend",
    description: "Wrangler + Workers tooling. We run on this today; we also compete on DX.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "cloudflare",
    repo: "pages-action",
    displayName: "Cloudflare Pages Action",
    priority: "high",
    category: "backend",
    description: "Official Pages deploy GitHub Action. Track deploy surface evolution.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "supabase",
    repo: "supabase",
    displayName: "Supabase",
    priority: "critical",
    category: "backend",
    description: "Open-source BaaS competitor. Auth + Postgres + edge functions.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "get-convex",
    repo: "convex-backend",
    displayName: "Convex",
    priority: "critical",
    category: "backend",
    description: "Reactive backend competitor. Sync engine + TS functions.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "superfly",
    repo: "flyctl",
    displayName: "Fly.io (flyctl)",
    priority: "high",
    category: "backend",
    description: "Firecracker microVM platform. Long-lived process competitor.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "renovatebot",
    repo: "renovate",
    displayName: "Renovate",
    priority: "medium",
    category: "backend",
    description: "We use Renovate; track feature evolution for self-evolution pipeline.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "railwayapp",
    repo: "cli",
    displayName: "Railway CLI",
    priority: "medium",
    category: "backend",
    description: "Railway PaaS competitor for deploy/runtime story.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "netlify",
    repo: "cli",
    displayName: "Netlify CLI",
    priority: "high",
    category: "backend",
    description: "Netlify deploy/edge competitor.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  // ── Accounting / Ledger Integration Targets (Astra vertical) ──────
  {
    owner: "XeroAPI",
    repo: "xero-node",
    displayName: "Xero Node SDK",
    priority: "medium",
    category: "api",
    description: "Xero accounting API client. Astra/ledger.ai integration & competitive surface.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  // ── QA / Security / Compliance Tooling (GateTest compete) ────────
  {
    owner: "codeclimate",
    repo: "codeclimate",
    displayName: "Code Climate CLI",
    priority: "medium",
    category: "api",
    description: "Code quality / maintainability scanner. GateTest competitor.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "codacy",
    repo: "codacy-analysis-cli-action",
    displayName: "Codacy Analysis Action",
    priority: "medium",
    category: "api",
    description: "Codacy static analysis GitHub Action. GateTest competitor.",
    defaultBranch: "master",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  {
    owner: "snyk",
    repo: "snyk",
    displayName: "Snyk CLI",
    priority: "high",
    category: "api",
    description: "Snyk vulnerability/security scanner. GateTest + compliance competitor.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  // ── Voice / Transcription (voice vertical) ────────────────────────
  {
    owner: "openai",
    repo: "whisper",
    displayName: "OpenAI Whisper",
    priority: "high",
    category: "ai",
    description: "ASR model powering voice/transcription. Track releases and ecosystem forks.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
  // ── AI Website Builders (Zoobicon compete) ────────────────────────
  {
    owner: "stackblitz",
    repo: "bolt.new",
    displayName: "StackBlitz Bolt",
    priority: "critical",
    category: "ai",
    description: "AI website builder direct competitor. WebContainers + LLM-driven codegen.",
    defaultBranch: "main",
    lastKnownRelease: null,
    lastKnownReleaseAt: null,
    lastCommitCheckAt: null,
    baselineCommitsPerWeek: null,
  },
];

export const SEARCH_KEYWORDS = [
  "AI framework",
  "web framework",
  "WebGPU",
  "edge computing",
  "CRDT",
  "SolidJS",
  "browser AI",
  "real-time collaboration",
];

export const TRACKED_NPM_PACKAGES = [
  "next",
  "remix",
  "svelte",
  "@sveltejs/kit",
  "astro",
  "hono",
  "solid-js",
  "@solidjs/start",
  "@trpc/server",
  "@trpc/client",
  "ai",
  "@ai-sdk/openai",
  "langchain",
  "@langchain/core",
  "drizzle-orm",
  "yjs",
  "zod",
];
