#!/usr/bin/env bun
/**
 * Generates apps/web/public/sitemap.xml and robots.txt from the current
 * routes and the PUBLIC_URL env var. Run at build time via the prebuild
 * script in apps/web/package.json.
 *
 * The moment you set PUBLIC_URL=https://yourdomain.com, this script
 * regenerates both files with your real domain.
 */

import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const PUBLIC_URL = process.env["PUBLIC_URL"] ?? "http://localhost:3000";
const ROUTES_DIR = join(import.meta.dir, "..", "apps", "web", "src", "routes");
const PUBLIC_DIR = join(import.meta.dir, "..", "apps", "web", "public");

// Routes that should NOT be indexed (private / auth-gated / dynamic)
const PRIVATE_ROUTES = new Set([
  "dashboard",
  "settings",
  "admin",
  "billing",
  "database",
  "ai-playground",
  "chat",
  "repos",
  "builder",
  "video",
  "collab",
  "templates",
]);

// Priority hints for important public pages
const PRIORITY: Record<string, string> = {
  "/": "1.0",
  "/pricing": "0.9",
  "/about": "0.8",
  "/docs": "0.8",
  "/status": "0.5",
  "/login": "0.3",
  "/register": "0.7",
};

interface RouteInfo {
  path: string;
  priority: string;
  changefreq: string;
}

async function discoverRoutes(): Promise<RouteInfo[]> {
  const routes: RouteInfo[] = [];

  // Top-level routes
  const entries = await readdir(ROUTES_DIR, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith(".tsx")) {
      const name = entry.name.replace(/\.tsx$/, "");
      // Skip dynamic and catch-all routes
      if (name.startsWith("[") || name.startsWith("(")) continue;
      // Skip private routes
      if (PRIVATE_ROUTES.has(name)) continue;

      const path = name === "index" ? "/" : `/${name}`;
      routes.push({
        path,
        priority: PRIORITY[path] ?? "0.6",
        changefreq: name === "index" ? "weekly" : "monthly",
      });
    }
  }

  // Legal routes
  try {
    const legalEntries = await readdir(join(ROUTES_DIR, "legal"), {
      withFileTypes: true,
    });
    for (const entry of legalEntries) {
      if (entry.isFile() && entry.name.endsWith(".tsx")) {
        const name = entry.name.replace(/\.tsx$/, "");
        routes.push({
          path: `/legal/${name}`,
          priority: "0.4",
          changefreq: "yearly",
        });
      }
    }
  } catch {
    // legal/ may not exist
  }

  return routes.sort((a, b) => a.path.localeCompare(b.path));
}

function buildSitemap(routes: RouteInfo[]): string {
  const today = new Date().toISOString().split("T")[0];
  const urls = routes
    .map(
      (r) => `  <url>
    <loc>${PUBLIC_URL}${r.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function buildRobotsTxt(): string {
  return `# robots.txt for ${PUBLIC_URL}
# Generated by scripts/generate-sitemap.ts

User-agent: *
Allow: /

# Block private routes
Disallow: /api/
Disallow: /dashboard
Disallow: /settings
Disallow: /admin
Disallow: /billing
Disallow: /database
Disallow: /ai-playground

Sitemap: ${PUBLIC_URL}/sitemap.xml
`;
}

async function main(): Promise<void> {
  const routes = await discoverRoutes();
  const sitemap = buildSitemap(routes);
  const robots = buildRobotsTxt();

  await writeFile(join(PUBLIC_DIR, "sitemap.xml"), sitemap, "utf-8");
  await writeFile(join(PUBLIC_DIR, "robots.txt"), robots, "utf-8");

  console.log(`[sitemap] Generated for ${PUBLIC_URL}`);
  console.log(`[sitemap] ${routes.length} public routes:`);
  for (const route of routes) {
    console.log(`  - ${route.path}`);
  }
}

void main();
