#!/usr/bin/env bun
// ── generate-changelog — AI-authored release notes for Crontech ────
//
// Reads commits from `git log` since the most recent boundary marker
// in CHANGELOG.md, then asks Claude Haiku (via the ai-core wrapper)
// to draft three sections:
//
//   1. user-facing release notes (marketing-polite, no competitor names)
//   2. internal dev notes (technical, breaking changes, migrations)
//   3. a single tweet-style social snippet (< 280 chars)
//
// Output goes to:
//   - CHANGELOG.md           (prepended, with a new boundary marker)
//   - docs/changelog/<date>.md
//   - docs/changelog/<date>.json   (for the admin UI to render)
//
// Usage:
//   bun run scripts/generate-changelog.ts [--from=<sha>|<YYYY-MM-DD>] [--dry-run]
//
// Defaults:
//   --from = most recent boundary in CHANGELOG.md (or repo root if none)
//   --to   = HEAD
//
// In dry-run mode (or when ANTHROPIC_API_KEY is missing), no Claude
// calls are made — the script prints the commits it WOULD send and a
// stub of the output it WOULD write. Tests mock the Claude client and
// assert the file contents directly.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { z } from "../packages/schemas/src/index";

// ── Public types ──────────────────────────────────────────────────

export interface CommitRecord {
  readonly sha: string;
  readonly shortSha: string;
  readonly subject: string;
  readonly author: string;
  readonly date: string; // ISO 8601
}

export interface ChangelogSections {
  readonly userNotes: string;
  readonly devNotes: string;
  readonly social: string;
}

export interface ChangelogPayload {
  readonly date: string; // YYYY-MM-DD
  readonly fromBoundary: string | null;
  readonly toSha: string;
  readonly commitCount: number;
  readonly commits: ReadonlyArray<CommitRecord>;
  readonly sections: ChangelogSections;
}

// A small interface so tests can mock Claude without hitting the wire.
export interface ClaudeClient {
  readonly complete: (prompt: string) => Promise<string>;
}

// ── Zod schemas validating Claude's responses ─────────────────────

export const UserNotesSchema = z
  .string()
  .min(20, "user notes must be at least 20 chars")
  .max(4000, "user notes are suspiciously long");

export const DevNotesSchema = z
  .string()
  .min(20, "dev notes must be at least 20 chars")
  .max(8000, "dev notes are suspiciously long");

export const SocialSchema = z
  .string()
  .min(10, "social snippet must be at least 10 chars")
  .max(280, "social snippet must be 280 chars or fewer");

export const ChangelogSectionsSchema = z.object({
  userNotes: UserNotesSchema,
  devNotes: DevNotesSchema,
  social: SocialSchema,
});

// ── Constants ─────────────────────────────────────────────────────

const BOUNDARY_RE = /<!--\s*changelog-boundary:(\d{4}-\d{2}-\d{2})\s*-->/g;
const REPO_ROOT = process.cwd();
const CHANGELOG_PATH = join(REPO_ROOT, "CHANGELOG.md");
const CHANGELOG_DOCS_DIR = join(REPO_ROOT, "docs", "changelog");

const HAIKU_MODEL = "claude-haiku-4-20250506";

// ── CLI argument parsing ──────────────────────────────────────────

export interface CliArgs {
  readonly from: string | undefined;
  readonly dryRun: boolean;
}

export function parseArgs(argv: ReadonlyArray<string>): CliArgs {
  let from: string | undefined;
  let dryRun = false;
  for (const raw of argv) {
    if (raw === "--dry-run") {
      dryRun = true;
    } else if (raw.startsWith("--from=")) {
      const value = raw.slice("--from=".length).trim();
      if (value.length > 0) from = value;
    }
  }
  return { from, dryRun };
}

// ── Boundary marker handling ──────────────────────────────────────

/**
 * Returns the most recent (i.e. lexicographically largest) boundary
 * date found in the supplied CHANGELOG.md text, or `null` if none.
 */
export function findLatestBoundary(changelogText: string): string | null {
  const dates: string[] = [];
  for (const m of changelogText.matchAll(BOUNDARY_RE)) {
    const captured = m[1];
    if (captured !== undefined) dates.push(captured);
  }
  if (dates.length === 0) return null;
  dates.sort();
  return dates[dates.length - 1] ?? null;
}

/**
 * Returns the seed CHANGELOG.md contents for a brand-new repo.
 * Includes a single boundary marker dated today plus a brief format
 * explanation so humans reading the file understand the convention.
 */
export function seedChangelog(today: string): string {
  return [
    "# Crontech Changelog",
    "",
    "This file is generated by `scripts/generate-changelog.ts`. It collects",
    "commits since the previous boundary marker, hands them to Claude Haiku,",
    "and writes three sections per release:",
    "",
    "- **User notes** — polite release notes for end users.",
    "- **Dev notes** — technical changes, breaking changes, and migration steps.",
    "- **Social snippet** — a single tweet-length announcement.",
    "",
    "Each release is bracketed by a boundary marker that the next run keys",
    "off when picking up where the last one left off:",
    "",
    "```",
    "<!-- changelog-boundary:YYYY-MM-DD -->",
    "```",
    "",
    "Do not edit boundary markers by hand. The generator manages them.",
    "",
    `<!-- changelog-boundary:${today} -->`,
    "",
  ].join("\n");
}

// ── Git helpers ───────────────────────────────────────────────────

/**
 * Resolves the `--from` argument or the latest boundary into a git
 * revision suitable for `git log <rev>..HEAD`. A YYYY-MM-DD value is
 * translated to `--since=<date>`. A 7+ char hex string is treated as
 * a sha. `null` means "from repo root".
 */
export function resolveFromRevision(
  fromArg: string | undefined,
  boundary: string | null,
): { kind: "sha" | "since" | "root"; value: string } {
  const candidate = fromArg ?? boundary ?? undefined;
  if (candidate === undefined) return { kind: "root", value: "" };
  if (/^\d{4}-\d{2}-\d{2}$/.test(candidate)) {
    return { kind: "since", value: candidate };
  }
  if (/^[0-9a-f]{7,40}$/i.test(candidate)) {
    return { kind: "sha", value: candidate };
  }
  // Unknown format → fall back to date interpretation if it's parseable.
  const parsed = new Date(candidate);
  if (!Number.isNaN(parsed.getTime())) {
    const iso = parsed.toISOString().slice(0, 10);
    return { kind: "since", value: iso };
  }
  // Last resort: treat as a sha-ish ref.
  return { kind: "sha", value: candidate };
}

/**
 * Reads commits between `from` (exclusive) and HEAD via `git log`.
 * Pure-IO helper; tests provide commit data directly via the
 * collaborators rather than shelling out.
 */
export function readCommitsFromGit(
  rev: ReturnType<typeof resolveFromRevision>,
): CommitRecord[] {
  const args = ["log", "--pretty=format:%H%x1f%h%x1f%an%x1f%aI%x1f%s%x1e"];
  if (rev.kind === "sha") {
    args.push(`${rev.value}..HEAD`);
  } else if (rev.kind === "since") {
    args.push(`--since=${rev.value}`);
  }
  // kind === "root" → no extra arg, full history.

  const result = spawnSync("git", args, {
    cwd: REPO_ROOT,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (result.status !== 0) {
    const stderr = result.stderr ?? "";
    throw new Error(`git log failed: ${stderr.trim() || "non-zero exit"}`);
  }
  return parseGitLog(result.stdout ?? "");
}

/** Parses the unit-separated git-log output produced by `readCommitsFromGit`. */
export function parseGitLog(raw: string): CommitRecord[] {
  const records: CommitRecord[] = [];
  for (const chunk of raw.split("\x1e")) {
    const trimmed = chunk.trim();
    if (trimmed.length === 0) continue;
    const parts = trimmed.split("\x1f");
    if (parts.length < 5) continue;
    const [sha, shortSha, author, date, subject] = parts;
    if (!sha || !shortSha || !author || !date || !subject) continue;
    records.push({ sha, shortSha, author, date, subject });
  }
  return records;
}

// ── Prompts ───────────────────────────────────────────────────────

function renderCommitList(commits: ReadonlyArray<CommitRecord>): string {
  return commits
    .map((c) => `- ${c.shortSha} ${c.subject} (${c.author}, ${c.date})`)
    .join("\n");
}

export function buildUserNotesPrompt(
  commits: ReadonlyArray<CommitRecord>,
  sinceLabel: string,
): string {
  return [
    `Here are ${commits.length} commits from Crontech since ${sinceLabel}.`,
    "",
    renderCommitList(commits),
    "",
    "Write 3-6 bullet user-facing release notes.",
    "Polite tone. No competitor names. Focus on what users can now DO.",
    "Omit internal refactors, lint fixes, and dependency bumps.",
    "Reply with the bullets only — no preamble, no closing remarks.",
  ].join("\n");
}

export function buildDevNotesPrompt(
  commits: ReadonlyArray<CommitRecord>,
  sinceLabel: string,
): string {
  return [
    `The same ${commits.length} commits from Crontech since ${sinceLabel}:`,
    "",
    renderCommitList(commits),
    "",
    "Write technical release notes for engineers.",
    "Cover: each commit's impact, any breaking changes, any migration steps.",
    "Plain engineering English. No marketing tone. No emojis.",
    "Group related commits where it helps clarity.",
    "Reply with the notes only — no preamble.",
  ].join("\n");
}

export function buildSocialPrompt(
  commits: ReadonlyArray<CommitRecord>,
  sinceLabel: string,
): string {
  return [
    `The same ${commits.length} commits from Crontech since ${sinceLabel}:`,
    "",
    renderCommitList(commits),
    "",
    "Write ONE tweet-style announcement under 280 characters.",
    "No marketing buzzwords. No emojis unless they earn their place.",
    "Reply with the tweet text only — nothing else.",
  ].join("\n");
}

// ── Claude client ─────────────────────────────────────────────────

/**
 * Builds a real Claude client backed by the `@back-to-the-future/ai-core`
 * Anthropic wrapper. Returns `null` if no `ANTHROPIC_API_KEY` is present;
 * callers are expected to fall back to dry-run mode in that case.
 */
export async function buildDefaultClaudeClient(): Promise<ClaudeClient | null> {
  const apiKey = process.env["ANTHROPIC_API_KEY"];
  if (!apiKey || apiKey.length < 6) return null;

  // Lazy-load the wrapper so dry-run / test paths don't pull in
  // heavyweight ai-sdk modules unnecessarily.
  const { getAnthropicModel } = await import("@back-to-the-future/ai-core");
  const { generateText } = await import("ai");
  const model = getAnthropicModel(apiKey, HAIKU_MODEL);

  return {
    complete: async (prompt: string): Promise<string> => {
      const result = await generateText({ model, prompt });
      return result.text.trim();
    },
  };
}

// ── Section generation ────────────────────────────────────────────

/**
 * Issues the three Claude calls and validates each response with Zod.
 * Sequential rather than parallel because the three prompts are tiny
 * and serializing avoids spurious 429s on cold accounts.
 */
export async function generateSections(
  client: ClaudeClient,
  commits: ReadonlyArray<CommitRecord>,
  sinceLabel: string,
): Promise<ChangelogSections> {
  const userRaw = await client.complete(buildUserNotesPrompt(commits, sinceLabel));
  const devRaw = await client.complete(buildDevNotesPrompt(commits, sinceLabel));
  const socialRaw = await client.complete(buildSocialPrompt(commits, sinceLabel));
  return ChangelogSectionsSchema.parse({
    userNotes: userRaw.trim(),
    devNotes: devRaw.trim(),
    social: socialRaw.trim(),
  });
}

// ── Output rendering ──────────────────────────────────────────────

export function renderMarkdownEntry(payload: ChangelogPayload): string {
  return [
    `## ${payload.date}`,
    "",
    `_${payload.commitCount} commits since ${payload.fromBoundary ?? "repo start"} (HEAD ${payload.toSha.slice(0, 7)})._`,
    "",
    "### User notes",
    "",
    payload.sections.userNotes,
    "",
    "### Dev notes",
    "",
    payload.sections.devNotes,
    "",
    "### Social snippet",
    "",
    payload.sections.social,
    "",
    `<!-- changelog-boundary:${payload.date} -->`,
    "",
  ].join("\n");
}

/**
 * Inserts the new entry above the most recent existing boundary so
 * the file reads newest-first. If no boundary exists, the entry is
 * appended after the seed header.
 */
export function prependEntry(existing: string, entry: string): string {
  // Find the FIRST boundary in document order — that marks where the
  // last entry was written, so we slip the new entry above it.
  const re = /<!--\s*changelog-boundary:\d{4}-\d{2}-\d{2}\s*-->/;
  const match = re.exec(existing);
  if (!match) {
    return `${existing.trimEnd()}\n\n${entry.trimStart()}`;
  }
  const idx = match.index;
  // Walk back to the start of the line containing the marker so we
  // don't split mid-line.
  const lineStart = existing.lastIndexOf("\n", idx) + 1;
  const before = existing.slice(0, lineStart).trimEnd();
  const after = existing.slice(lineStart);
  return `${before}\n\n${entry.trimStart()}\n${after}`;
}

// ── Main orchestration ────────────────────────────────────────────

export interface RunOptions {
  readonly args: CliArgs;
  readonly today: string;
  readonly client: ClaudeClient | null;
  readonly commits: ReadonlyArray<CommitRecord>;
  readonly headSha: string;
  readonly existingChangelog: string | null; // null if file absent
}

export interface RunResult {
  readonly mode: "dry-run" | "no-key" | "wrote";
  readonly payload: ChangelogPayload | null;
  readonly markdown: string | null;
  readonly nextChangelog: string | null;
  readonly logLines: ReadonlyArray<string>;
}

/**
 * Pure orchestration: takes resolved inputs (commits, options, client)
 * and returns what would be written, plus the human-readable log lines
 * the CLI would print. No filesystem writes. No git calls. Easy to
 * test exhaustively.
 */
export async function runGeneration(opts: RunOptions): Promise<RunResult> {
  const log: string[] = [];
  const boundary = opts.existingChangelog
    ? findLatestBoundary(opts.existingChangelog)
    : null;
  const sinceLabel = opts.args.from ?? boundary ?? "repo start";

  log.push(
    `Found ${opts.commits.length} commit(s) since ${sinceLabel} → HEAD ${opts.headSha.slice(0, 7)}.`,
  );

  if (opts.commits.length === 0) {
    log.push("Nothing to do. No new commits since the last boundary.");
    return { mode: "dry-run", payload: null, markdown: null, nextChangelog: null, logLines: log };
  }

  // Dry-run OR no API key → preview only.
  if (opts.args.dryRun || opts.client === null) {
    const reason = opts.args.dryRun ? "dry-run" : "no-key";
    log.push(
      reason === "dry-run"
        ? "Dry-run: skipping Claude calls. Would send the following commits:"
        : "ANTHROPIC_API_KEY not set: skipping Claude calls. Would send the following commits:",
    );
    for (const c of opts.commits) {
      log.push(`  ${c.shortSha} ${c.subject}`);
    }
    log.push("");
    log.push("Prompts that would be issued:");
    log.push(`  1. User notes — ${buildUserNotesPrompt(opts.commits, sinceLabel).split("\n")[0] ?? ""}`);
    log.push(`  2. Dev notes  — ${buildDevNotesPrompt(opts.commits, sinceLabel).split("\n")[0] ?? ""}`);
    log.push(`  3. Social     — ${buildSocialPrompt(opts.commits, sinceLabel).split("\n")[0] ?? ""}`);
    return { mode: reason, payload: null, markdown: null, nextChangelog: null, logLines: log };
  }

  log.push("Calling Claude Haiku for user notes, dev notes, and social snippet...");
  const sections = await generateSections(opts.client, opts.commits, sinceLabel);

  const payload: ChangelogPayload = {
    date: opts.today,
    fromBoundary: boundary,
    toSha: opts.headSha,
    commitCount: opts.commits.length,
    commits: opts.commits,
    sections,
  };
  const markdown = renderMarkdownEntry(payload);
  const base = opts.existingChangelog ?? seedChangelog(opts.today);
  const nextChangelog = prependEntry(base, markdown);

  log.push(`Generated entry for ${opts.today}.`);
  return { mode: "wrote", payload, markdown, nextChangelog, logLines: log };
}

// ── CLI entrypoint ────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const today = new Date().toISOString().slice(0, 10);

  const existing = existsSync(CHANGELOG_PATH)
    ? await readFile(CHANGELOG_PATH, "utf8")
    : null;

  const boundary = existing ? findLatestBoundary(existing) : null;
  const rev = resolveFromRevision(args.from, boundary);
  const commits = readCommitsFromGit(rev);

  const headResult = spawnSync("git", ["rev-parse", "HEAD"], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
  const headSha = (headResult.stdout ?? "").trim() || "0000000";

  const client = args.dryRun ? null : await buildDefaultClaudeClient();

  const result = await runGeneration({
    args,
    today,
    client,
    commits,
    headSha,
    existingChangelog: existing,
  });

  for (const line of result.logLines) {
    console.info(line);
  }

  if (result.mode !== "wrote" || !result.payload || !result.markdown || !result.nextChangelog) {
    return;
  }

  // Write CHANGELOG.md (or seed if absent), the per-date markdown, and the JSON sidecar.
  await writeFile(CHANGELOG_PATH, result.nextChangelog, "utf8");

  const datedMd = join(CHANGELOG_DOCS_DIR, `${today}.md`);
  const datedJson = join(CHANGELOG_DOCS_DIR, `${today}.json`);
  await mkdir(dirname(datedMd), { recursive: true });
  await writeFile(datedMd, result.markdown, "utf8");
  await writeFile(datedJson, `${JSON.stringify(result.payload, null, 2)}\n`, "utf8");

  console.info(`Wrote ${CHANGELOG_PATH}`);
  console.info(`Wrote ${datedMd}`);
  console.info(`Wrote ${datedJson}`);
}

// Only run when invoked directly, not when imported by tests.
const invokedDirectly = (() => {
  const entry = process.argv[1];
  if (!entry) return false;
  return entry.endsWith("generate-changelog.ts") || entry.endsWith("generate-changelog");
})();

if (invokedDirectly) {
  main().catch((err) => {
    console.error("generate-changelog failed:", err);
    process.exit(1);
  });
}
