import { For } from "solid-js";
import type { JSX } from "solid-js";
import { Stack, Text, Card } from "@back-to-the-future/ui";
import { SEOHead } from "../../components/SEOHead";

interface Section { title: string; content: string }

const sections: Section[] = [
  { title: "1. Notification of Infringement", content: "[ATTORNEY REVIEW REQUIRED] If you believe that content on our Service infringes your copyright, please send a notification containing: (a) identification of the copyrighted work; (b) identification of the infringing material with sufficient detail to locate it; (c) your contact information; (d) a statement of good faith belief; (e) a statement under penalty of perjury that the information is accurate; (f) your physical or electronic signature." },
  { title: "2. Designated Agent", content: "[ATTORNEY REVIEW REQUIRED] DMCA Agent: [NAME], [EMAIL], [MAILING ADDRESS]. Registered with the U.S. Copyright Office." },
  { title: "3. Counter-Notification", content: "[ATTORNEY REVIEW REQUIRED] If you believe your content was removed in error, you may submit a counter-notification containing: (a) identification of the removed material; (b) a statement under penalty of perjury that you have a good faith belief the material was removed by mistake; (c) your name, address, and telephone number; (d) consent to jurisdiction; (e) your physical or electronic signature." },
  { title: "4. Repeat Infringer Policy", content: "[ATTORNEY REVIEW REQUIRED] We will terminate accounts of users who are repeat infringers of copyright, in appropriate circumstances as determined by us in our sole discretion." },
  { title: "5. AI-Generated Content Notice", content: "[ATTORNEY REVIEW REQUIRED] Content generated by AI features on our platform may inadvertently resemble copyrighted works. Users are responsible for ensuring AI-generated content does not infringe third-party rights before publishing or distributing." },
];

export default function DMCAPage(): JSX.Element {
  return (
    <>
      <SEOHead
        title="DMCA Policy"
        description="DMCA takedown policy for Back to the Future. How to report copyright infringement and counter-notification procedures."
        path="/legal/dmca"
      />
      <Stack direction="vertical" gap="lg" class="page-padded legal-page">
        <Stack direction="vertical" gap="sm">
          <Text variant="h1" weight="bold">DMCA Policy</Text>
          <Text variant="caption" class="text-muted">Last updated: [DATE]</Text>
        </Stack>
        <For each={sections}>
          {(section) => (
            <Card padding="md">
              <Stack direction="vertical" gap="sm">
                <Text variant="h4" weight="semibold">{section.title}</Text>
                <Text variant="body">{section.content}</Text>
              </Stack>
            </Card>
          )}
        </For>
      </Stack>
    </>
  );
}
