import { For } from "solid-js";
import type { JSX } from "solid-js";
import { Stack, Text, Card } from "@back-to-the-future/ui";
import { SEOHead } from "../../components/SEOHead";

interface Section { title: string; content: string }

const sections: Section[] = [
  { title: "1. Acceptance of Terms", content: "[ATTORNEY REVIEW REQUIRED] By accessing or using the Back to the Future platform (\"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, you may not access or use the Service." },
  { title: "2. Description of Service", content: "[ATTORNEY REVIEW REQUIRED] Back to the Future provides an AI-native full-stack platform for website building, video editing, and real-time collaboration. The Service includes AI-powered tools, collaborative editing features, and related services." },
  { title: "3. User Accounts & Registration", content: "[ATTORNEY REVIEW REQUIRED] You must register for an account to access certain features. You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate, current, and complete information during registration." },
  { title: "4. Acceptable Use Policy", content: "[ATTORNEY REVIEW REQUIRED] You agree not to use the Service for any unlawful purpose or in violation of these Terms. You may not use the Service to generate harmful, deceptive, or illegal content. See our full Acceptable Use Policy for details." },
  { title: "5. Intellectual Property", content: "[ATTORNEY REVIEW REQUIRED] The Service and its original content, features, and functionality are owned by Back to the Future and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws." },
  { title: "6. User Content & Data", content: "[ATTORNEY REVIEW REQUIRED] You retain all rights to content you create using the Service. By using the Service, you grant us a limited license to process your content as necessary to provide the Service. We do not claim ownership of your content." },
  { title: "7. AI-Generated Content", content: "[ATTORNEY REVIEW REQUIRED] Content generated by AI features is provided \"as is\" without warranty of accuracy, completeness, or fitness for any particular purpose. You are responsible for reviewing and validating all AI-generated content before use. AI-generated content may not be suitable for legal, medical, or other professional purposes without human review." },
  { title: "8. Payment Terms", content: "[ATTORNEY REVIEW REQUIRED] Paid features are billed through Stripe. Subscription fees are billed in advance on a monthly or annual basis. You authorize us to charge your payment method for all fees due. Refund policies and billing disputes are handled per our refund policy." },
  { title: "9. Service Availability & SLA", content: "[ATTORNEY REVIEW REQUIRED] We strive for high availability but do not guarantee uninterrupted service. Scheduled maintenance will be communicated in advance. Enterprise customers may negotiate specific SLA terms." },
  { title: "10. Limitation of Liability", content: "[ATTORNEY REVIEW REQUIRED] TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BACK TO THE FUTURE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES." },
  { title: "11. Indemnification", content: "[ATTORNEY REVIEW REQUIRED] You agree to indemnify and hold harmless Back to the Future, its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from your use of the Service or violation of these Terms." },
  { title: "12. Termination", content: "[ATTORNEY REVIEW REQUIRED] We may terminate or suspend your account at any time for any reason. Upon termination, your right to use the Service will immediately cease. You may terminate your account at any time through the Settings page." },
  { title: "13. Governing Law & Dispute Resolution", content: "[ATTORNEY REVIEW REQUIRED] These Terms shall be governed by and construed in accordance with the laws of [JURISDICTION]. Any disputes arising under these Terms shall be resolved through [ARBITRATION/LITIGATION] in [VENUE]." },
  { title: "14. Changes to Terms", content: "[ATTORNEY REVIEW REQUIRED] We reserve the right to modify these Terms at any time. Material changes will be communicated via email or in-app notification at least 30 days before taking effect. Continued use after changes constitutes acceptance." },
  { title: "15. Contact Information", content: "[ATTORNEY REVIEW REQUIRED] For questions about these Terms, contact us at: [EMAIL ADDRESS], [MAILING ADDRESS]." },
];

export default function TermsPage(): JSX.Element {
  return (
    <>
      <SEOHead
        title="Terms of Service"
        description="Terms of Service for the Back to the Future platform. Read about usage rights, AI-generated content, payments, and more."
        path="/legal/terms"
      />
      <Stack direction="vertical" gap="lg" class="page-padded legal-page">
        <Stack direction="vertical" gap="sm">
          <Text variant="h1" weight="bold">Terms of Service</Text>
          <Text variant="caption" class="text-muted">Last updated: [DATE] | Effective: [DATE]</Text>
        </Stack>
        <For each={sections}>
          {(section) => (
            <Card padding="md">
              <Stack direction="vertical" gap="sm">
                <Text variant="h4" weight="semibold">{section.title}</Text>
                <Text variant="body">{section.content}</Text>
              </Stack>
            </Card>
          )}
        </For>
      </Stack>
    </>
  );
}
